require("mini.pick").setup()
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', ":Pick grep<CR>")
vim.keymap.set('n', '<leader>vh', builtin.help_tags, {})
