#!/usr/bin/env bash

_tdm_completion() {
    local tasks=("clear" "new" "ls" "lsd" "lstd" "set-done" "set-due")
    local cur_word="${COMP_WORDS[COMP_CWORD]}"
    local prev_word="${COMP_WORDS[COMP_CWORD-1]}"

    case "$prev_word" in
        ls*|set-*)
            COMPREPLY=($(compgen -W "" -- "$cur_word"))
            return
            ;;
    esac

    COMPREPLY=($(compgen -W "${tasks[*]}" -- "$cur_word"))
}

complete -F _tdm_completion tdm

